# Generated by Django 3.2.5 on 2021-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210814_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='member',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
