# Generated by Django 3.2.5 on 2021-08-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210815_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='paid_until',
        ),
    ]
