# Generated by Django 3.2.5 on 2021-07-28 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20210728_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
