# Generated by Django 3.2.5 on 2021-08-04 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='Bodybuilding', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='forum.category'),
        ),
    ]
