# Generated by Django 3.2.5 on 2021-08-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20210814_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sku',
        ),
    ]
