# Generated by Django 3.2.5 on 2021-08-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
